apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app.kubernetes.io/name: simple-go-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-go-app
    spec:
      containers:
      - image: fitrihono01/test_app:go
        name: go
        ports:
        - containerPort: 8081